import type { Preview } from '@storybook/web-components-vite';
import { html } from 'lit';

// Built brand tokens — base dark theme. Generated by `npm run build` at the
// repo root (build/css is git-ignored, so run the build before Storybook).
// Importing the CSS defines every --color-*/--font-*/--spacing-* custom
// property on :root, which is all the rr-* components need to theme.
import '../../../build/css/variables.css';

const preview: Preview = {
  parameters: {
    // The canvas is themed by the decorator below + preview-head.html, so the
    // built-in backgrounds addon would only fight the token-driven surface.
    backgrounds: { disable: true },
    controls: { expanded: true },
  },
  decorators: [
    (story) => html`
      <div
        style="
          background: var(--color-background-default);
          color: var(--color-foreground-default);
          font: var(--font-body-large);
          padding: var(--spacing-component);
          min-height: 100vh;
          box-sizing: border-box;
        "
      >
        ${story()}
      </div>
    `,
  ],
};

export default preview;
